project:
  type: website
  output-dir: docs


website:
  title: "Nostradamus_CB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
        

format:
  html:
    theme:
      - cosmo-book
    
    css: styles.css
    toc: true
 

editor: visual

