project:
  type: website
  output-dir: docs
 

website:
  #title: "UNIGE and UNEP/GRID-Geneva data cubes capacity building"
  
  
  sidebar:
    style: "docked"
    collapse-level: 1
    logo: images/NOSTRADAMUS_logo.png
    search: true
    contents:
      - text: Home
        href: index.qmd
      - section: "Introduction to datacubes"  
        href: dc_introduction.qmd
        contents:
          - text: Installation
            href: dc_installation.qmd
          - text: Quick Start
            href: dc_quickstart.qmd
      - section: "Nostradamus datacube"
        contents:
          - text: Overview
            href: nostradamus_datacube_overview.qmd
          - text: Datacube install
            href: nostradamus_datacube_setup.qmd
          - text: Datacube use
            href: nostradamus_datacube_use.qmd
    
          
     # - section: "Monalisa datacube"
       # contents:
       #   - text: Overview
        #    href: monalisa_datacube.qmd
        #  - text: Datacube install
       #     href: monalisas_datacube_setup.qmd
       #   - text: Datacube use
        #    href: monalisa_datacube_setup.qmd
      # - text: Definitions
       # href: definitions.qmd
      - section: Tutorials
        href: tutorials.qmd
        contents: 
          - text: How to index new data into a DC?
            href: 1_new_data_into_dc.qmd
          - text: How to retrieve data using the Python API?
            href: 2_retrieve_data_python_api.qmd
          #- text:
         #   href: tutorial3.qmd    
      - section: Vector datacubes
        href: vector_dc_overview.qmd
        contents: 
           - text: Installation
             href: vector_dc_installation.qmd
      - section: Data sources
        href: data_sources.qmd
        contents: 
          - landsat.qmd
          - sentinel.qmd
          - planetary_computer.qmd    
     
      - text: Acknowledgments
        href: acknowledgments.qmd
      - text: FAQ
        href: faq.qmd
      - section: "Appendices"
        contents:
          - text: Jupyter
            href: jupyter.qmd
     
          
     # - href: concepts.qmd
     #   text: Concepts
    
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
 

editor: visual

