project:
  type: website
  output-dir: docs
 

website:
  title: "UNIGE and UNEP/GRID-Geneva data cubes capacity building"
  
  
  sidebar:
    style: "docked"
    collapse-level: 1
    #logo: images/NOSTRADAMUS_logo.png
    search: true
    contents:
      - text: Home
        href: index.qmd
      - section: "Nostradamus datacube"
        contents:
          - text: Overview
            href: nostradamus_datacube_overview.qmd
          - text: Datacube install
            href: nostradamus_datacube_setup.qmd
          - text: Datacube use
            href: nostradamus_datacube_setup.qmd
          
     # - section: "Monalisa datacube"
       # contents:
       #   - text: Overview
        #    href: monalisa_datacube.qmd
        #  - text: Datacube install
       #     href: monalisas_datacube_setup.qmd
       #   - text: Datacube use
        #    href: monalisa_datacube_setup.qmd
      - text: Definitions
        href: definitions.qmd
      - section: Data sources
        href: data_sources.qmd
        contents: 
          - sentinel.qmd
          - planetary_computer.qmd    
     
      - section: "Appendices"
        contents:
          - text: Jupyter
            href: jupyter.qmd
     
          
     # - href: concepts.qmd
     #   text: Concepts
    
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
 

editor: visual

