---
title: "Nostradamus datacube installation"
---

::: {.callout-note}
A [detailed installation procedure](https://git.unepgrid.ch/NOSTRADAMUS/cube-in-a-box-jupyter/src/branch/main#readme){target="_blank"} and other [admin and user tutorials](https://git.unepgrid.ch/NOSTRADAMUS/cube-in-a-box-jupyter/src/branch/main/docs){target="_blank"} exist. The steps below consist in additional help to the links mentioned for a Docker install of the Nostradamus data cube
:::

1)  Install [Docker desktop](https://www.docker.com/products/docker-desktop){target="_blank"} for your operating system and launch it

2)  To make sure all works fine, type the following commands in your Terminal (example on Mac OS):

``` markdown
docker –-version 
```
and

``` markdown
docker compose version
```

If corresponding information is returned, it means all is working fine for your Docker session and you can proceed to the next steps

3)  Clone the Nostradamus jupyter cube into your local Docker application by typing the following command: 

``` markdown
git clone https://git.unepgrid.ch/NOSTRADAMUS/cube-in-a-box-jupyter.git
```

This will create a cube-in-a-box-jupyter folder with all the necessary Docker files. In case the folder already exists, use the pull command (more info in the [FAQ](faq.qmd){target="_blank"} page)

4)  Once the installation is finalized, go to the newly created folder by typing in your Terminal 

``` markdown
cd cube-in-a-box-jupyter
```


5)  Use then the `make setup` command to initiate the datacube before using it. You can either simply type `make setup`, which will deploy the datacube with all layers available, or you can filter a specific area of interest using the BBOX parameter (e.g. `make setup BBOX=5.95,45.81,10.50,47.81`) and the DATETIME parameter specifying a particular time range (e.g. `make setup BBOX=5.95,45.81,10.50,47.81 DATETIME=2024-01-01/2024-12-31`)
